"""empty message

Revision ID: 059ef76c193d
Revises: 46019f534d8f
Create Date: 2021-03-12 18:47:41.425955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '059ef76c193d'
down_revision = '46019f534d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_1', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('question_2', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('question_3', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('question_4', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('question_5', mysql.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
