"""empty message

Revision ID: 1e47671ce3b5
Revises: 3a8dde6255b4
Create Date: 2021-03-15 23:04:38.778974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e47671ce3b5'
down_revision = '3a8dde6255b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio', 'question_1',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('portfolio', 'question_2',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('portfolio', 'question_3',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('portfolio', 'question_4',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('portfolio', 'question_5',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio', 'question_5',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('portfolio', 'question_4',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('portfolio', 'question_3',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('portfolio', 'question_2',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('portfolio', 'question_1',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
