"""empty message

Revision ID: 3a8dde6255b4
Revises: 059ef76c193d
Create Date: 2021-03-13 01:26:16.395098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8dde6255b4'
down_revision = '059ef76c193d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_1', sa.String(length=120), nullable=False),
    sa.Column('question_2', sa.String(length=120), nullable=False),
    sa.Column('question_3', sa.String(length=120), nullable=False),
    sa.Column('question_4', sa.String(length=120), nullable=False),
    sa.Column('question_5', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio')
    # ### end Alembic commands ###
