"""empty message

Revision ID: 5300a349e179
Revises: ad4b30225f56
Create Date: 2021-03-27 04:12:01.996793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5300a349e179'
down_revision = 'ad4b30225f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question1', sa.String(length=120), nullable=True),
    sa.Column('question2', sa.String(length=120), nullable=True),
    sa.Column('question3', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
