"""empty message

Revision ID: ad4b30225f56
Revises: 
Create Date: 2021-03-23 00:48:33.343192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4b30225f56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_1', sa.String(length=120), nullable=True),
    sa.Column('question_2', sa.String(length=120), nullable=True),
    sa.Column('question_3', sa.String(length=120), nullable=True),
    sa.Column('question_4', sa.String(length=120), nullable=True),
    sa.Column('question_5', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(length=120), nullable=True),
    sa.Column('quantity', sa.String(length=120), nullable=True),
    sa.Column('symbol', sa.String(length=120), nullable=True),
    sa.Column('total_purchase', sa.String(length=120), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaction')
    op.drop_table('portfolio')
    # ### end Alembic commands ###
